name: Auto Assign on Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assign:
    if: github.event.issue.pull_request == null
    runs-on: ubuntu-latest

    steps:
      - name: Check for /assign comment
        if: contains(github.event.comment.body, '/assign')
        run: |
          echo "Assign command detected"

      - name: Assign the commenter
        if: contains(github.event.comment.body, '/assign')
        uses: actions/github-script@v7
        with:
          script: |
            const commenter = context.payload.comment.user.login;
            const issue_number = context.payload.issue.number;
            const repo = context.repo;

            console.log(`Assigning ${commenter} to issue #${issue_number}`);

            await github.rest.issues.addAssignees({
              owner: repo.owner,
              repo: repo.repo,
              issue_number,
              assignees: [commenter],
            });